.TH EXPOSE-FILEMANAGER 1 "Mar 2, 2017"
.SH NAME
expose-filemanager.py \- Expose freedesktop dbus to Thunar
.SH SYNOPSIS
.B expose-filemanager
.SH DESCRIPTION
.B EXPOSE-FILEMANAGER
The expose-filemanager.py script exposes a dbus object that implements the
freedesktop File Manager DBus specification.

.SH SEE ALSO
Mainline: https://github.com/dirk-olmes/dbus-file-manager
.PP
.SH AUTHOR
This man page was write by Matias De lellis <mati86dl@gmail.com>
